services:
  # =========================
  # SERVICIO BACKEND
  # =========================
  backend:
    build: .
    container_name: backend-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network

  # =========================
  # SERVICIO MYSQL
  # =========================
  mysql:
    image: kamilox25/data-ev2:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    # La definimos como externa porque ya la creamos con el comando manual
    external: true